### PR TITLE
Fix cucumber-js reporter for @cucumber/messages v22 (ESM compatibility)

### PR DESCRIPTION
**Pull request by BrunoNCD**
Addresses issue #442 

Also removed a random .png artifact that makes it impossible to clone on windows (yeah, windows amirite.)

### CODE REVIEW

**Comment by BrunoNCD** [comment]
image

No lint issues, built and tested on my project and it works.

**Comment by PatrickBlink** [comment]
Hi @BrunoNCD any idea why this change hasn't been merged? 🤔 Thanks 🙏

**Comment by felipocorrea90** [comment]
is it possible to merge these changes. The project as it is doesn't seem to work for CucumberJS. Still getting Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/src/messages' is not defined by "exports" ...

**Comment by PatrickBlink** [comment]
Hard to see why but it seems that this issue won't be worked on further. Quite strange given that the job has been done and needed to be merged.

**Pull request closed without merging**
