### PR TITLE
feat: qase-core-reporter

### PR DESCRIPTION
**Pull request by dimitriharding**
The existing qase JS reporters all use a set of standard functions and logic to properly send results to Qase.io.  This PR is to create a base core reporter that any existing reporter can be refactored to use, or even create new javascript reporters faster by using. 

To demonstrate usage, there is an examples folder that shows how all of the existing reporters could be refactored to use this core module, while still supporting existing features and using less code. 

---
####  Unit tests:
reduce-test-time

- [vitest](https://vitest.dev) is used for the test runner instead of jest
-  [Mock Service Worker](https://mswjs.io/) is used to intercept calls to the qase.io, which gives good control over responses and not having to mock function implementations
- Currently, it takes about ~16secs~ < 5s to complete all tests (~83~ 92 in total)
- The test execution time ~could possibly be reduced if we split the tests in multiple files (if there is a need)~ has been reduced by splitting tests into multiple files, I believe this brings organization since it's lots of tests and the by-product is faster execution.
- Coverage is not 100% mainly because ~of the `result-bulk-detached.js` file, where for some reporters we have to finish reporting in a child process, and when this is done, the requests going out to qase.io cannot be intercepted (at least not with the current setup)~ the lines remaining I could not create any scenario that reaches that code, which could possibly mean, those conditions won't exist but I left them just in case.
- Added an `npm run test:ci` command for running the tests in run mode when running in the pipeline, this will ensure that the test execution does not hang in watch mode on CI. 

---
#### How to run examples:
1. Build the qase-core-reporter 
	`cd qase-core-reporter`
    `npm run dev:watch`
2. Build the example reporter you want to test in a new terminal
    `cd qase-core-reporter/examples/jest-reporter`
    `npm run dev:watch`
3. Update the example reporter example test project with valid API key and Project ID, and then run tests as normal
   `npm run test`

### CODE REVIEW

**Comment by jamesmortensen** [comment]
Will this work if our test app is using mocha and chai expect?  What about WebdriverIO with the @wdio/mocha-framework?  qase-mocha and wdio-qase-reporter are two reporters that would be useful to build on top of this base.  Thank you!

**Comment by sharovatov** [comment]
@jamesmortensen thanks for your comment! In this very task @dimitriharding is creating a new solid core that would allow us to add any other autotesting frameworks very easily. As soon as this particular task is done and completed, we will start working on adding more frameworks, mocha and chai of course too!

**Comment by 1ivliev** [comment]
@dimitriharding Can you cover the two remaining vulnerabilities? I think after that we will be able to merge PR
https://sonarcloud.io/project/security_hotspots?id=qase-tms_qase-javascript&pullRequest=275&sinceLeakPeriod=true

**Comment by dimitriharding** [comment]
@1ivliev  I looked at these, and I believe they are non-issues. Maybe the team can review and update SonarCloud to mark these as such. 

As seen below,  `node` and `npm` are being flagged since we did not provide the full path to these executables. 

Xnapper-2022-10-02-08 07 58

Since the paths to these vary based on the environment it is somewhat expected to be accessed through the application’s PATH environment variable (not providing a full path). 

Also, these commands will most likely never be changed to anything malicious since this module will be run in a controlled nodejs environment.

**Comment by 1ivliev** [comment]
@nl-kaidzen can u take a look at this?

**Comment by bormando** [comment]
@1ivliev @nl-kaidzen when are we expecting this to be released? "Shortly" is coming for months already.

**Review by n3r — APPROVED** [review]

**Pull request merged**
